version: '2'
services:
  # NGINX REVERSE PROXY
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: "proxy"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    environment:
      DEFAULT_HOST: default.sokka.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs-volume:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"
  nginx-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: "proxy_ssl"
    restart: always
    volumes:
      - "certs-volume:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "proxy"
  # FALLBACK (DEFAULT)
  default:
    image: nginx
    container_name: "sokka.me"
    restart: always
    networks:
      - proxy_default
      - default 
    volumes:
      - ./default:/code
      - ./default:/usr/share/nginx/html
      - ./default/site.conf:/etc/nginx/conf.d/000_site.conf
    expose:
      - 8001
    ports:
      - "8001:80"
    environment:
      - NGINX_HOST=sokka.me
      - NGINX_PORT=80
      - VIRTUAL_HOST=sokka.me,www.sokka.me
      - LETSENCRYPT_HOST=sokka.me,www.sokka.me
      - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
  php:
    container_name: "sokka.me_php"
    image: php:7-fpm
    volumes:
      - ./default:/code
volumes:
  certs-volume: "./proxy/certs"
