version: '2'
services:
  # NGINX REVERSE PROXY
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: "sokka_proxy"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    environment:
      DEFAULT_HOST: default.sokka.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs-volume:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./proxy.conf:/etc/nginx/conf.d"
  nginx-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: "sokka_proxy_ssl"
    restart: always
    volumes:
      - "certs-volume:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "proxy"
  # MAIN PAGE
  main:
    depends_on:
      - proxy
    image: nginx
    container_name: "sokka.me"
    restart: always 
    volumes:
      - ./main/html:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=sokka.me
      - NGINX_PORT=80
      - VIRTUAL_HOST=sokka.me,www.sokka.me
      - LETSENCRYPT_HOST=sokka.me,www.sokka.me
      - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
# API PAGE
  api:
    depends_on:
      - proxy
      - db
    container_name: "api.sokka.me"
    image: htl-anichstrasse/sokka
    restart: always
    ports:
     - "1234:80"
    environment:
     - NGINX_HOST=api.sokka.me
     - NGINX_PORT=80
     - PORT=1234
     - VIRTUAL_PORT=1234
     - VIRTUAL_HOST=api.sokka.me
     - LETSENCRYPT_HOST=api.sokka.me
     - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
  db:
    image: mariadb
    container_name: "api.sokka.me_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verycoolpassword
# DEFAULT PAGE (FALLBACK)
  default:
    depends_on:
      - proxy
    container_name: "default.sokka.me"
    image: nginx
    restart: always 
    volumes:
      - ./default:/usr/share/nginx/html
    ports:
     - "8082:80"
    environment:
     - NGINX_HOST=default.sokka.me
     - NGINX_PORT=80
     - VIRTUAL_HOST=bemoty.prox.kaifink.me
     - LETSENCRYPT_HOST=bemoty.prox.kaifink.me
     - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
volumes:
  certs-volume:
