version: "2"
services:
  # NGINX REVERSE PROXY
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: "sokka_proxy"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    environment:
      - DEFAULT_HOST=default.sokka.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs-volume:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./proxy.conf:/etc/nginx/conf.d"
  nginx-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: "sokka_proxy_ssl"
    restart: always
    volumes:
      - "certs-volume:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "proxy"
  # MAIN PAGE
  main:
    depends_on:
      - proxy
    image: nginx
    container_name: "sokka.me"
    restart: always
    volumes:
      - ./main/html:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=sokka.me
      - NGINX_PORT=80
      - VIRTUAL_HOST=sokka.me,www.sokka.me
      - LETSENCRYPT_HOST=sokka.me,www.sokka.me
      - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
  # API PAGE
  api:
    depends_on:
      - proxy
      - mysql
    container_name: "api.sokka.me"
    image: htl-anichstrasse/sokka:v1
    restart: always
    ports:
      - "8090:8090"
    environment:
      - NGINX_HOST=api.sokka.me
      - NGINX_PORT=8090
      - PORT=8090
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=E6s2hYPSD6os3FaP
      - MYSQL_DB=sokka
      - VIRTUAL_PORT=8090
      - VIRTUAL_HOST=api.sokka.me
      - LETSENCRYPT_HOST=api.sokka.me
      - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
  mysql:
    image: mysql:latest
    container_name: "api.sokka.me_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "api.sokka.me_pma"
    restart: always
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - NGINX_HOST=pma.sokka.me
      - VIRTUAL_PORT=8095
      - VIRTUAL_HOST=pma.sokka.me
      - LETSENCRYPT_HOST=pma.sokka.me
      - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
    ports:
      - "8095:80"
  acp:
    depends_on:
      - proxy
    container_name: "acp.sokka.me"
    image: nginx
    restart: always
    volumes:
      - ./acp/build:/usr/share/nginx/html
      - ./acp/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8065:80"
    environment:
      - NGINX_HOST=acp.sokka.me
      - NGINX_PORT=80
      - VIRTUAL_HOST=acp.sokka.me
      - HTTPS_METHOD=noredirect
      - LETSENCRYPT_HOST=acp.sokka.me
      - LETSENCRYPT_EMAIL=jos.winkler@tsn.at
  # DEFAULT PAGE (FALLBACK)
  default:
    depends_on:
      - proxy
    container_name: "default.sokka.me"
    image: nginx
    restart: always
    volumes:
      - ./default:/usr/share/nginx/html
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=default.sokka.me
      - NGINX_PORT=80
      - VIRTUAL_HOST=default.sokka.me
      - HTTPS_METHOD=noredirect
volumes:
  certs-volume:
